name: dask
channels:
  - conda-forge
  - defaults
dependencies:
  - argon2-cffi=20.1.0
  - attrs=19.3.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - blas=1.0
  - bleach=3.1.5
  - blosc=1.19.0
  - bokeh=2.1.1
  - boto3=1.14.35
  - botocore=1.17.35
  - brotlipy=0.7.0
  - ca-certificates=2020.6.24
  - certifi=2020.6.20
  - cffi=1.14.0
  - chardet=3.0.4
  - click=7.1.2
  - cloudpickle=1.5.0
  - cryptography=3.0
  - cytoolz=0.10.1
  - dask=2.20.0
  - dask-core=2.20.0
  - decorator=4.4.2
  - defusedxml=0.6.0
  - distributed=2.20.0
  - docutils=0.15.2
  - entrypoints=0.3
  - fastparquet=0.4.0
  - freetype=2.10.2
  - fsspec=0.7.4
  - heapdict=1.0.1
  - idna=2.10
  - importlib-metadata=1.7.0
  - importlib_metadata=1.7.0
  - ipykernel=5.3.4
  - ipython=5.8.0
  - ipython_genutils=0.2.0
  - jinja2=2.11.2
  - jmespath=0.10.0
  - jpeg=9b
  - json5=0.9.4
  - jsonschema=3.2.0
  - jupyter_client=6.1.6
  - jupyter_core=4.6.3
  - jupyterlab=2.2.2
  - jupyterlab_server=1.2.0
  - lcms2=2.11
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcxx=10.0.1
  - libedit=3.1.20191231
  - libffi=3.2.1
  - liblapack=3.8.0
  - libopenblas=0.3.10
  - libpng=1.6.37
  - libsodium=1.0.18
  - libtiff=4.1.0
  - llvm-openmp=10.0.1
  - locket=0.2.0
  - lz4-c=1.9.2
  - markupsafe=1.1.1
  - mistune=0.8.4
  - msgpack-python=1.0.0
  - nbconvert=5.6.1
  - nbformat=5.0.7
  - ncurses=6.2
  - nomkl=3.0
  - notebook=6.1.1
  - numpy=1.19.1
  - numpy-base=1.19.1
  - olefile=0.46
  - openblas=0.3.10
  - openssl=1.1.1g
  - packaging=20.4
  - pandas=1.0.5
  - pandoc=2.10.1
  - pandocfilters=1.4.2
  - partd=1.1.0
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=7.2.0
  - pip=20.1.1
  - prometheus_client=0.8.0
  - prompt_toolkit=1.0.15
  - psutil=5.7.0
  - ptyprocess=0.6.0
  - pycparser=2.20
  - pygments=2.6.1
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyrsistent=0.16.0
  - pysocks=1.7.1
  - python=3.7.7
  - python-blosc=1.7.0
  - python-dateutil=2.8.1
  - python_abi=3.7
  - pytz=2020.1
  - pyyaml=5.3.1
  - pyzmq=19.0.2
  - readline=8.0
  - requests=2.24.0
  - s3fs=0.4.2
  - s3transfer=0.3.3
  - scipy=1.5.0
  - send2trash=1.5.0
  - setuptools=49.2.0
  - simplegeneric=0.8.1
  - six=1.15.0
  - snappy=1.1.8
  - sortedcontainers=2.2.2
  - sqlite=3.32.3
  - tblib=1.6.0
  - terminado=0.8.3
  - testpath=0.4.4
  - tk=8.6.10
  - toolz=0.10.0
  - tornado=6.0.4
  - traitlets=4.3.3
  - typing_extensions=3.7.4.2
  - urllib3=1.25.10
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.34.2
  - xz=5.2.5
  - yaml=0.2.5
  - zeromq=4.3.2
  - zict=2.0.0
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - cycler==0.10.0
    - joblib==0.16.0
    - kiwisolver==1.2.0
    - llvmlite==0.33.0
    - matplotlib==3.3.0
    - numba==0.50.1
    - pyarrow==1.0.0
    - scikit-learn==0.23.2
    - seaborn==0.10.1
    - threadpoolctl==2.1.0
    - thrift==0.13.0
    - xgboost==1.1.1
prefix: /var/lib/conda/envs/dask

